### ISSUE TITLE
Picker is not woking with Fast-Render

### ISSUE THREAD

**Issue by WooGenius** [meteorhacks/picker#22] opened 2015-08-27 02:33 UTC
Hi, @arunoda.

I currently update meteor version to 1.1.0.3. And I found Picker is not working with Fast-Render.
When I use server side route, Fast-Render can't inject data. But when I turn off server side route, Fast-render is working properly. Maybe it's a `next()` function bug?

Thanks in advance.

**Comment by arunoda** [comment] 2015-08-27 03:10
Could you isolate this and send me a sample app?

**Comment by WooGenius** [comment] 2015-08-27 03:11
Yeah I'll Thanks.

**Comment by WooGenius** [comment] 2015-08-27 07:58
@arunoda 
Sample App: http://fast-render-picker-example.meteor.com/with-fast-render
Code: https://github.com/WooGenius/fast-render-with-picker-example

When I use server side route and fast-render at the same time, Fast render data is not injected.
You can check on '/with-fast-render-and-server-side-route`.

**Comment by Primigenus** [comment] 2015-08-29 06:09
I just ran into this issue too.

**Comment by arunoda** [comment] 2015-08-29 06:19
Let's see. I will fix this today.

**Comment by newswim** [comment] 2015-09-20 22:03
Was this issue resolved?

**Comment by Primigenus** [comment] 2015-09-25 03:12
@arunoda D:

**Comment by arunoda** [comment] 2015-09-25 12:45
@WooGenius Here's the situation. FastRender also use Picker behind the scene.
In this case, both FR and your code register a route.

So, your code wins but not FR's route. We don't pass multiple route handlers for a single route.
May be we should try to throw an error.

So, I suggest you to use a middleware instead to do your stuff. See below:

```js
  Picker.middleware(function (request, response, next) {
    if(request.url === "/with-fast-render-and-server-side-route") {
      console.log("Pass through server side route");
    }

    next();
  });
```

**Comment by arunoda** [comment] 2015-09-25 12:46
@Primigenus I was about to look at this issue. But this was lost in my mailbox. Thanks @Primigenus  and @newswim for reminding this.

BTW: I'm gonna close this issue since this is not a bug, but a question.

**Closed by arunoda** 2015-09-25 12:46 UTC

**Comment by WooGenius** [comment] 2015-09-25 13:15
@Arunoda Thanks! I'll try
